server:
  port: 10010

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/custom?useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5                                         # 初始化连接数
      max-total: 5                                            # 最大连接数
      max-wait-millis: 200                                    # 等待连接获取的最大超时时间
      min-idle: 5                                             # 数据库连接池的最小维持连接数

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update
entitymanager:
  packagesToScan: com.jack.entity


eureka:
  client:
    service-url:
      #defaultZone: http://localhost:9001/eureka
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9003.com:9003/eureka/
  instance:
    instance-id: microservice-hibernate10010            #自定义服务名称信息
    prefer-ip-address: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html  #指定eurka注册改服务的访问地址

#redis:
#  keys: order
#  order:
#    host: 114.55.130.145
#    port: 6379
#    password: tst_test
#    dbIndex: 0
#    timeOut: 2000
#    pool:
#      maxActive: 10
#      maxIdle: 5
#      minIdle: 1
#      maxWait: 2000
#      testOnBorrow: true