spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev                   #开发环境
  application:
    name: microservice-provider #修改后 调服务也须修改

---
spring:
  profiles: test                  #测试环境
  application:
    name: microservice-config-test
