spring:
  profiles:
    active:
      - dev

---
server:
  port: 7003

spring:
  profiles: dev
  application:
    name: microservice-consumer-config-clent

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka9003.com:9003/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

---
server:
  port: 7004

spring:
  profiles: test
  application:
    name: microservice-consumer-config-clent

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka9003.com:9003/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/
