eureka:
  instance:
    hostname: eureka9001
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka9003.com:9003/eureka/,http://eureka9002.com:9002/eureka/
#    service-url: 只有一个服务写法如下
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 9001
